# frozen_string_literal: true

source 'https://rubygems.org'

gem 'activerecord', '~> 7.1'
gem 'activesupport', '~> 7.1'
gem 'amazing_print', '~> 1.4.0'
gem 'bunny', '~> 2.19'
gem 'dotenv', '~> 2.7'
gem 'dry-initializer', '~> 3.0.3'
gem 'faraday', '~> 1.0.1'
gem 'faraday_middleware', '~> 1.0.0'
# json 3.x removed the create_additions: keyword that Rack::JSONBodyParser
# (rack-contrib 2.5.0) still passes, which turns every JSON request body into a
# 400. rubocop's "json >= 2.3" would otherwise pull 3.x in here.
gem 'json', '~> 2.7'
gem 'jsonapi-serializer', '~> 2.2'
gem 'kaminari-activerecord', '~> 1.2'
gem 'pg', '~> 1.2'
gem 'pry', '~> 0.14'
gem 'puma', '~> 5.5'
gem 'rack', '~> 2.2'
gem 'rack-contrib', '~> 2.3'
gem 'rack-ougai', '~> 0.2.1'
gem 'rack-request-id', '~> 0.0.4'
gem 'railties', '~> 7.1'
gem 'rake', '~> 13.0'
gem 'require_all', '~> 3.0'
gem 'rubocop', '~> 1.21'
gem 'sinatra', '~> 2.1'
gem 'sinatra-activerecord', '~> 2.0'
gem 'sinatra-contrib', '~> 2.1'
gem 'sinatra-strong-params', '~> 0.1', require: 'sinatra/strong-params'
